### ISSUE TITLE
make make-time look more like gmail

### ISSUE THREAD

**Issue by erikus** [ojanvafai/make-time#108]
I'd like to style a few things like the background color using a custom style sheet but the elements mostly have inline styles and lack IDs and classes, making this difficult.

**Comment by erikus** [comment]
I mostly got around this with the following:

body {
    font-family: Roboto;
    font-size: 10pt;
}

#drawer + div {
    background-color: #b2d5ee !important;
}

select.button, button, .label-button {
    font-size: 10pt !important;
}

so this is low priority for me now.

**Comment by erikus** [comment]
A few font family and font size tweaks goes pretty far. A configurable background would be nice, too.

**Comment by ojanvafai** [comment]
I made the font sizes smaller on desktop. I think they were a good size for mobile for the touch targets to be big enough.

The font-family was already roboto, so I think that was a noop.

Only thing I didn't do was background color.

**Comment by erikus** [comment]
Thanks!

**Comment by ojanvafai** [comment]
Ugh...I went to make background-color a setting and it's kind of annoying. We create the AppShell before we've logged in, so we don't have the settings data. I suppose we could change the background color once we load settings....but...I think I"m not going to bother unless other folks want this. 

Patches welcome though if someone does want it.
