### ISSUE TITLE
Sometimes archiving doesn't correctly hide threads.

### ISSUE THREAD

**Issue by tdresser** [ojanvafai/make-time#17]
What I see:
* Select a bunch of issues.
* Hit archive
* Some of the selected issues go away, others sit there, highlighted.
* Refresh the page.
* All issues I tried to archive are now archived.

**Comment by ojanvafai** [comment]
https://github.com/ojanvafai/make-time/commit/b0fbd5d874761a44ba608335e01a7b986f779949
