### ISSUE TITLE
Finish keyboard shortcuts for threadlist view

### ISSUE THREAD

**Issue by tdresser** [ojanvafai/make-time#2]

**Comment by tdresser** [comment]
- indicate a "selected" row.
- spacebar toggles checkbox for selected row.
-up/j moves selection up
-down/k moves selection down
- shift spacebar makes all checkboxes ...mumble mumble... up to and including the selection take on the value opposite the current selection.
That last one I'm actually pretty fuzzy on.

**Comment by ojanvafai** [comment]
This is done except for the shift-spacebar bit, right?

**Comment by tdresser** [comment]
My plan has changed a bit, let me know how this sounds.
In particular, I don't think I actually care about range selection, but I do care about group toggling.

TODO:
1. Make toggling with mouse move focus.
2. n/p move to next/previous group
3. Some shortcut toggles everything in the current group.
