### ISSUE TITLE
Calendar View: split up unbooked time.

### ISSUE THREAD

**Issue by tdresser** [ojanvafai/make-time#35]
Split unbooked time up by size of block.

**Comment by ojanvafai** [comment]
https://github.com/ojanvafai/make-time/commit/c9a197dfc606a7d899c0a695c9a70ea1d6b6dfb0

I went with small <= 30m, medium <=60m, and large >60m as an initial guess of what useful values might be. Open to changing those constants though or adding more/fewer buckets.

@tessamac in case you have feels.
