### ISSUE TITLE
running local server requires being given deploy permissions :(

### ISSUE THREAD

**Issue by erikus** [ojanvafai/make-time#50]
When I follow the README instructions to run a test server locally I get an authorization error. This happens with and without the --google flag. I did a firebase authentication flow with my google address prior to running the following:

```
% ./gulp serve --google
Error: Authorization failed. This account is missing the following required permissions on project mk-time:

  firebase.projects.get

Having trouble? Try firebase serve --help
[21:36:41] 'firebase-serve' errored after 1.33 s
[21:36:41] Error in plugin "gulp-shell"
Message:
    Command `./node_modules/firebase-tools/lib/bin/firebase.js serve --project mk-time --port=8000` failed with exit code 1
[21:36:41] 'serve' errored after 6.94 s
[21:36:41] The following tasks did not complete: tsc-watch
[21:36:41] Did you forget to signal async completion?
```

**Comment by ojanvafai** [comment]
Ugh. Yeah, this is something dumb with firebase that I havne't had time to figure out yet. It seems crazy that you need to be added to the deployment servers just to start a local server. For now I added your google.com address to the public deployment of maketime (--project mk-time shoudl work at that point). Once you accept hte invitation it should work. When I get to a work computer I'll add you to the work deployment as well.
