### ISSUE TITLE
Respond from email address that you received email to

### ISSUE THREAD

**Issue by tdresser** [ojanvafai/make-time#76]

**Comment by ojanvafai** [comment]
Looks like the Delivered-To header is what we need to get the address. I just looked at a blink-dev thread to see which header had my chromium.org address. We could unconditionally user Delivered-To, but maybe we should be properly integrating multisender support using https://developers.google.com/gmail/api/v1/reference/users/settings/sendAs and then changing the default selected sender based off Delivered-To?

**Comment by ojanvafai** [comment]
The only hard part of the sendAs thing is figuring out how to incorporate a sender UI into the reply UI. I guess we could jsut put a dropdown to the right of the cancel button below "reply all". Although...really that UI needs a fair bit of rethought as I find myself really wanting the ability to forward messages.
