### ISSUE TITLE
Make-Time mode should support Archive hotkey

### ISSUE THREAD

**Issue by tdresser** [ojanvafai/make-time#8]
We aren't starting with the reply box focused (which I think is correct), so we might as well support the archive hotkey.

**Comment by ojanvafai** [comment]
Hah...the reply box is supposed to be focused! I was thinking that was the correct thing. Isn't what you want to do usually to reply?

Regardless, when the reply box isn't focused, the hotkey should work. So this bug is still valid. Easy to fix. I just forgot to hook up some code.

**Comment by ojanvafai** [comment]
https://github.com/ojanvafai/make-time/commit/f132cd40203d87c1658ec2e0dc26945b63f063a8
